export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const LOGIN_ERR = 'AUTH_ERR';
export const SIGNUP_ERR = 'SIGNUP_ERR';
export const LOGIN_LOADING = 'LOGIN_LOADING';
export const SIGNUP_LOADING = 'SIGNUP_LOADING';
export const AUTH_RESET = 'AUTH_RESET';
export const UPDATE_USER_DATA = 'UPDATE_USER_DATA';

export const SET_NOTIFS = 'SET_NOTIFS';
export const DELETE_NOTIF = 'DELETE_NOTIF';

export const CREATE_BOARD = 'CREATE_BOARD';
export const TOGGLE_IS_STARRED = 'TOGGLE_IS_STARRED';
export const UPDATE_ACTIVE_BOARD = 'UPDATE_ACTIVE_BOARD';
export const UPDATE_BOARD_TITLE = 'UPDATE_BOARD_TITLE';
export const ADD_ADMIN = 'ADD_ADMIN';
export const REMOVE_ADMIN = 'REMOVE_ADMIN';
export const DEMOTE_SELF = 'DEMOTE_SELF';
export const UPDATE_COLOR = 'UPDATE_COLOR';
export const UPDATE_BOARD_DESC = 'UPDATE_BOARD_DESC';

export const UPDATE_LIST_TITLE = 'UPDATE_LIST_TITLE';
export const ADD_LIST = 'ADD_LIST';

export const ADD_CARD = 'ADD_CARD';
export const SET_CARD_DETAILS = 'SET_CARD_DETAILS';
export const UPDATE_CARD_TITLE = 'UPDATE_CARD_TITLE';
export const UPDATE_CARD_DESC = 'UPDATE_CARD_DESC';
export const ADD_CARD_LABEL = 'ADD_CARD_LABEL';
export const REMOVE_CARD_LABEL = 'REMOVE_CARD_LABEL';
