export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const LOGIN_ERR = 'AUTH_ERR';
export const SIGNUP_ERR = 'SIGNUP_ERR';
export const LOGIN_LOADING = 'LOGIN_LOADING';
export const SIGNUP_LOADING = 'SIGNUP_LOADING';
export const AUTH_RESET = 'AUTH_RESET';
export const UPDATE_USER_DATA = 'UPDATE_USER_DATA';

export const SET_NOTIFS = 'SET_NOTIFS';
export const DELETE_NOTIF = 'DELETE_NOTIF';

export const CREATE_BOARD = 'CREATE_BOARD';
export const TOGGLE_IS_STARRED = 'TOGGLE_IS_STARRED';
export const TOGGLE_IS_STARRED_ACTIVE = 'TOGGLE_IS_STARRED_ACTIVE';
export const UPDATE_ACTIVE_BOARD = 'UPDATE_ACTIVE_BOARD';
export const UPDATE_BOARD_TITLE = 'UPDATE_BOARD_TITLE';
export const ADD_ADMIN = 'ADD_ADMIN';
export const REMOVE_ADMIN = 'REMOVE_ADMIN';
export const DEMOTE_SELF = 'DEMOTE_SELF';
export const UPDATE_COLOR = 'UPDATE_COLOR';
export const UPDATE_BOARD_DESC = 'UPDATE_BOARD_DESC';
export const UPDATE_REFRESH_ENABLED = 'UPDATE_REFRESH_ENABLED';
export const DELETE_BOARD = 'DELETE_BOARD';

export const UPDATE_LIST_TITLE = 'UPDATE_LIST_TITLE';
export const ADD_LIST = 'ADD_LIST';
export const COPY_LIST = 'COPY_LIST';
export const ARCHIVE_LIST = 'ARCHIVE_LIST';
export const RECOVER_LIST = 'RECOVER_LIST';
export const DELETE_LIST = 'DELETE_LIST';

export const ADD_CARD = 'ADD_CARD';
export const SET_CARD_DETAILS = 'SET_CARD_DETAILS';
export const UPDATE_CARD_TITLE = 'UPDATE_CARD_TITLE';
export const UPDATE_CARD_DESC = 'UPDATE_CARD_DESC';
export const ADD_CARD_LABEL = 'ADD_CARD_LABEL';
export const REMOVE_CARD_LABEL = 'REMOVE_CARD_LABEL';
export const TOGGLE_DUE_DATE = 'TOGGLE_DUE_DATE';
export const ADD_DUE_DATE = 'ADD_DUE_DATE';
export const REMOVE_DUE_DATE = 'REMOVE_DUE_DATE';
export const ADD_CHECKLIST = 'ADD_CHECKLIST';
export const DELETE_CHECKLIST = 'DELETE_CHECKLIST';
export const ADD_CHECKLIST_ITEM = 'ADD_CHECKLIST_ITEM';
export const TOGGLE_CHECKLIST_ITEM = 'TOGGLE_CHECKLIST_ITEM';
export const EDIT_CHECKLIST_ITEM = 'EDIT_CHECKLIST_ITEM';
export const DELETE_CHECKLIST_ITEM = 'DELETE_CHECKLIST_ITEM';
export const COPY_CARD = 'COPY_CARD';
export const ARCHIVE_CARD = 'ARCHIVE_CARD';
export const RECOVER_CARD = 'RECOVER_CARD';
export const DELETE_CARD = 'DELETE_CARD';

export const MOVE_LIST = 'MOVE_LIST';
export const MOVE_CARD_SAME_LIST = 'MOVE_CARD_SAME_LIST';
export const MOVE_CARD_DIFF_LIST = 'MOVE_CARD_DIFF_LIST';
